import { buildSummaryPrompt } from '../llm/prompts.js';

// Marker embedded in summary comments — used to find and update existing comments
// instead of posting duplicates on every `synchronize` event
const SUMMARY_MARKER = '<!-- PR-AI-AGENT:SUMMARY -->';

// Module 1: PR Auto-Summarizer
// Fetches PR diff + metadata → generates SAP-aware summary → posts/updates PR comment
export async function runSummarizer(github, llm, owner, repo, prNumber) {
  console.log(`[Summarizer] Starting for PR #${prNumber}`);

  const [prDetails, changedFiles, diffText] = await Promise.all([
    github.getPRDetails(owner, repo, prNumber),
    github.getChangedFiles(owner, repo, prNumber),
    github.getPRDiff(owner, repo, prNumber),
  ]);

  console.log(`[Summarizer] Fetched ${changedFiles.length} changed files`);

  const { system, user } = buildSummaryPrompt(prDetails, changedFiles, diffText);

  // Get LLM summary (no confidence calculation here - that's in reviewer module)
  const response = await llm.complete(system, user, 1024);
  const summaryText = typeof response === 'object' && response.text ? response.text : response;

  const commentBody = formatSummaryComment(summaryText, changedFiles, prDetails);

  // Upsert: update existing comment if found, otherwise create new
  const existing = await github.findAgentComment(owner, repo, prNumber, SUMMARY_MARKER);
  if (existing) {
    await github.updateComment(owner, repo, existing.id, commentBody);
    console.log(`[Summarizer] Updated existing comment #${existing.id}`);
  } else {
    await github.postComment(owner, repo, prNumber, commentBody);
    console.log('[Summarizer] Posted new summary comment');
  }

  return summaryText;
}

function formatSummaryComment(summaryText, changedFiles, prDetails) {
  const fileStats = buildFileStats(changedFiles);
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  return `${SUMMARY_MARKER}
# 📝 AI-Generated PR Summary

${summaryText}

---

<details>
<summary>📂 Changed Files (${changedFiles.length})</summary>

| Status | File | +/- |
|--------|------|-----|
${fileStats}
</details>

---

<sub>🤖 Generated by SAP-Copilot-Agent · ${timestamp} · Module 1: PR Summarizer · Commit \`${prDetails.head.sha.slice(0, 7)}\`</sub>`;
}

function buildFileStats(changedFiles) {
  return changedFiles
    .map((f) => {
      const statusIcon = { added: '🟢', removed: '🔴', modified: '🟡', renamed: '🔵' }[f.status] || '⚪';
      return `| ${statusIcon} ${f.status} | \`${f.filename}\` | +${f.additions} -${f.deletions} |`;
    })
    .join('\n');
}
